language: rust
sudo: false

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: nightly
      name: "no_std target"
      install:
        - rustup target add thumbv6m-none-eabi
      script:
        - cargo build --target=thumbv6m-none-eabi

script:
  - RUST_BACKTRACE=1 cargo test

notifications:
  email:
    on_success: never
