language: rust
sudo: false

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: nightly
      name: "no_std target"
      install:
        - rustup target add thumbv6m-none-eabi
      script:
        - cargo build --target=thumbv6m-none-eabi --no-default-features
    - name: "miri"
      install:
        - MIRI_NIGHTLY=nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/miri)
        - rustup set profile minimal
        - rustup default "$MIRI_NIGHTLY"
        - rustup component add miri
        - cargo miri setup
      script:
        - cargo miri test

script:
  - RUST_BACKTRACE=1 cargo test
  - RUST_BACKTRACE=1 cargo build --no-default-features

notifications:
  email:
    on_success: never
