[package]
name = "rcptr"
version = "0.1.0"
authors = ["Nika Layzell <nika@thelayzells.com>"]
edition = "2018"

[workspace]
members = ["rcptr-macros"]

[dependencies]
rcptr-macros = { version = "0.1.0", path = "rcptr-macros" }
